// Copyright 2026 Scriptforge
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @file Scriptforge.LanguageCode.ixx
 * @brief 定义了一个枚举类 `Language`，包含了多种语言的枚举值，以及两个映射表：一个将语言名称字符串映射到枚举值，另一个将 ISO-639-1 代码映射到枚举值。这些定义可以用于在脚本中处理不同语言相关的功能，如本地化、翻译等。
 * @author Scriptforge
 * @date 2026/3/29
 */

export module Scriptforge.LanguageCode;

import Scriptforge.Pch;

namespace Scriptforge::LanguageCode {

    /* -------------------------------------------------------------
     *  语言枚举定义（完整版本）
     * ------------------------------------------------------------- */
    export enum class Language : int {
        Neutral = 0x00,
        Invariant = 0x7f,
        Afrikaans = 0x36,
        Albanian = 0x1c,
        Amharic = 0x5e,
        Arabic = 0x01,
        Armenian = 0x2b,
        Assamese = 0x4d,
        Azerbaijani = 0x2c,
        Basque = 0x2d,
        Belarusian = 0x23,
        Bulgarian = 0x02,
        Catalan = 0x03,
        Chinese = 0x04,
        Croatian = 0x1a,
        Czech = 0x05,
        Danish = 0x06,
        Dutch = 0x13,
        English = 0x09,
        Estonian = 0x25,
        Faeroese = 0x38,
        Finnish = 0x0b,
        French = 0x0c,
        Frisian = 0x62,
        Galician = 0x56,
        Georgian = 0x37,
        German = 0x07,
        Greek = 0x08,
        Gujarati = 0x47,
        Hebrew = 0x0d,
        Hindi = 0x39,
        Hungarian = 0x0e,
        Icelandic = 0x0f,
        Indonesian = 0x21,
        Irish = 0x3c,
        Italian = 0x10,
        Japanese = 0x11,
        Kannada = 0x4b,
        Kazak = 0x3f,
        Khmer = 0x53,
        Korean = 0x12,
        Kyrgyz = 0x40,
        Latvian = 0x26,
        Lithuanian = 0x27,
        Macedonian = 0x2f,
        Malay = 0x3e,
        Malayalam = 0x4c,
        Maltese = 0x3a,
        Marathi = 0x4e,
        Mongolian = 0x50,
        Nepali = 0x61,
        Norwegian = 0x14,
        Persian = 0x29,
        Polish = 0x15,
        Portuguese = 0x16,
        Punjabi = 0x46,
        Romanian = 0x18,
        Russian = 0x19,
        Serbian = 0x1a,
        Slovak = 0x1b,
        Slovenian = 0x24,
        Spanish = 0x0a,
        Swahili = 0x41,
        Swedish = 0x1d,
        Tamil = 0x49,
        Tatar = 0x44,
        Telugu = 0x4a,
        Thai = 0x1e,
        Turkish = 0x1f,
        Ukrainian = 0x22,
        Urdu = 0x20,
        Uzbek = 0x43,
        Vietnamese = 0x2a,
        Welsh = 0x52,
        Xhosa = 0x34,
        Yi = 0x78,
        Yoruba = 0x6a,
        Zulu = 0x35
    };

    /* -------------------------------------------------------------
     *  语言名称到枚举的映射
     * ------------------------------------------------------------- */
    export inline const std::map<std::string, Language> LANG_NAME_TO_ENUM = {
        {"LANG_NEUTRAL", Language::Neutral},
        {"LANG_INVARIANT", Language::Invariant},
        {"LANG_AFRIKAANS", Language::Afrikaans},
        {"LANG_ALBANIAN", Language::Albanian},
        {"LANG_AMHARIC", Language::Amharic},
        {"LANG_ARABIC", Language::Arabic},
        {"LANG_ARMENIAN", Language::Armenian},
        {"LANG_ASSAMESE", Language::Assamese},
        {"LANG_AZERBAIJANI", Language::Azerbaijani},
        {"LANG_BASQUE", Language::Basque},
        {"LANG_BELARUSIAN", Language::Belarusian},
        {"LANG_BULGARIAN", Language::Bulgarian},
        {"LANG_CATALAN", Language::Catalan},
        {"LANG_CHINESE", Language::Chinese},
        {"LANG_CROATIAN", Language::Croatian},
        {"LANG_CZECH", Language::Czech},
        {"LANG_DANISH", Language::Danish},
        {"LANG_DUTCH", Language::Dutch},
        {"LANG_ENGLISH", Language::English},
        {"LANG_ESTONIAN", Language::Estonian},
        {"LANG_FAEROESE", Language::Faeroese},
        {"LANG_FINNISH", Language::Finnish},
        {"LANG_FRENCH", Language::French},
        {"LANG_FRISIAN", Language::Frisian},
        {"LANG_GALICIAN", Language::Galician},
        {"LANG_GEORGIAN", Language::Georgian},
        {"LANG_GERMAN", Language::German},
        {"LANG_GREEK", Language::Greek},
        {"LANG_GUJARATI", Language::Gujarati},
        {"LANG_HEBREW", Language::Hebrew},
        {"LANG_HINDI", Language::Hindi},
        {"LANG_HUNGARIAN", Language::Hungarian},
        {"LANG_ICELANDIC", Language::Icelandic},
        {"LANG_INDONESIAN", Language::Indonesian},
        {"LANG_IRISH", Language::Irish},
        {"LANG_ITALIAN", Language::Italian},
        {"LANG_JAPANESE", Language::Japanese},
        {"LANG_KANNADA", Language::Kannada},
        {"LANG_KAZAK", Language::Kazak},
        {"LANG_KHMER", Language::Khmer},
        {"LANG_KOREAN", Language::Korean},
        {"LANG_KYRGYZ", Language::Kyrgyz},
        {"LANG_LATVIAN", Language::Latvian},
        {"LANG_LITHUANIAN", Language::Lithuanian},
        {"LANG_MACEDONIAN", Language::Macedonian},
        {"LANG_MALAY", Language::Malay},
        {"LANG_MALAYALAM", Language::Malayalam},
        {"LANG_MALTESE", Language::Maltese},
        {"LANG_MARATHI", Language::Marathi},
        {"LANG_MONGOLIAN", Language::Mongolian},
        {"LANG_NEPALI", Language::Nepali},
        {"LANG_NORWEGIAN", Language::Norwegian},
        {"LANG_PERSIAN", Language::Persian},
        {"LANG_POLISH", Language::Polish},
        {"LANG_PORTUGUESE", Language::Portuguese},
        {"LANG_PUNJABI", Language::Punjabi},
        {"LANG_ROMANIAN", Language::Romanian},
        {"LANG_RUSSIAN", Language::Russian},
        {"LANG_SERBIAN", Language::Serbian},
        {"LANG_SLOVAK", Language::Slovak},
        {"LANG_SLOVENIAN", Language::Slovenian},
        {"LANG_SPANISH", Language::Spanish},
        {"LANG_SWAHILI", Language::Swahili},
        {"LANG_SWEDISH", Language::Swedish},
        {"LANG_TAMIL", Language::Tamil},
        {"LANG_TATAR", Language::Tatar},
        {"LANG_TELUGU", Language::Telugu},
        {"LANG_THAI", Language::Thai},
        {"LANG_TURKISH", Language::Turkish},
        {"LANG_UKRAINIAN", Language::Ukrainian},
        {"LANG_URDU", Language::Urdu},
        {"LANG_UZBEK", Language::Uzbek},
        {"LANG_VIETNAMESE", Language::Vietnamese},
        {"LANG_WELSH", Language::Welsh},
        {"LANG_XHOSA", Language::Xhosa},
        {"LANG_YI", Language::Yi},
        {"LANG_YORUBA", Language::Yoruba},
        {"LANG_ZULU", Language::Zulu}
    };

    /* -------------------------------------------------------------
     *  ISO-639-1 代码到枚举的映射
     * ------------------------------------------------------------- */
    export inline const std::map<std::string, Language> ISO639_1_TO_ENUM = {
        {"af", Language::Afrikaans},
        {"sq", Language::Albanian},
        {"am", Language::Amharic},
        {"ar", Language::Arabic},
        {"hy", Language::Armenian},
        {"as", Language::Assamese},
        {"az", Language::Azerbaijani},
        {"eu", Language::Basque},
        {"be", Language::Belarusian},
        {"bg", Language::Bulgarian},
        {"ca", Language::Catalan},
        {"zh", Language::Chinese},
        {"hr", Language::Croatian},
        {"cs", Language::Czech},
        {"da", Language::Danish},
        {"nl", Language::Dutch},
        {"en", Language::English},
        {"et", Language::Estonian},
        {"fo", Language::Faeroese},
        {"fi", Language::Finnish},
        {"fr", Language::French},
        {"fy", Language::Frisian},
        {"gl", Language::Galician},
        {"ka", Language::Georgian},
        {"de", Language::German},
        {"el", Language::Greek},
        {"gu", Language::Gujarati},
        {"he", Language::Hebrew},
        {"hi", Language::Hindi},
        {"hu", Language::Hungarian},
        {"is", Language::Icelandic},
        {"id", Language::Indonesian},
        {"ga", Language::Irish},
        {"it", Language::Italian},
        {"ja", Language::Japanese},
        {"kn", Language::Kannada},
        {"kk", Language::Kazak},
        {"km", Language::Khmer},
        {"ko", Language::Korean},
        {"ky", Language::Kyrgyz},
        {"lv", Language::Latvian},
        {"lt", Language::Lithuanian},
        {"mk", Language::Macedonian},
        {"ms", Language::Malay},
        {"ml", Language::Malayalam},
        {"mt", Language::Maltese},
        {"mr", Language::Marathi},
        {"mn", Language::Mongolian},
        {"ne", Language::Nepali},
        {"no", Language::Norwegian},
        {"fa", Language::Persian},
        {"pl", Language::Polish},
        {"pt", Language::Portuguese},
        {"pa", Language::Punjabi},
        {"ro", Language::Romanian},
        {"ru", Language::Russian},
        {"sr", Language::Serbian},
        {"sk", Language::Slovak},
        {"sl", Language::Slovenian},
        {"es", Language::Spanish},
        {"sw", Language::Swahili},
        {"sv", Language::Swedish},
        {"ta", Language::Tamil},
        {"tt", Language::Tatar},
        {"te", Language::Telugu},
        {"th", Language::Thai},
        {"tr", Language::Turkish},
        {"uk", Language::Ukrainian},
        {"ur", Language::Urdu},
        {"uz", Language::Uzbek},
        {"vi", Language::Vietnamese},
        {"cy", Language::Welsh},
        {"xh", Language::Xhosa},
        {"yi", Language::Yi},
        {"yo", Language::Yoruba},
        {"zu", Language::Zulu}
    };

    export inline const std::map<Language, std::string> ENUM_TO_LANG_NAME = []() {
        std::map<Language, std::string> m;
        for (const auto& pair : LANG_NAME_TO_ENUM) {
            m[pair.second] = pair.first;
        }
        return m;
		}();
    export inline const std::map<Language, std::string>& ENUM_TO_ISO639_1() {
        static const std::map<Language, std::string> ENUM_TO_ISO639_1 = {
            { Language::Afrikaans, "af" },
            { Language::Albanian, "sq" },
            { Language::Amharic, "am" },
            { Language::Arabic, "ar" },
            { Language::Armenian, "hy" },
            { Language::Assamese, "as" },
            { Language::Azerbaijani, "az" },
            { Language::Basque, "eu" },
            { Language::Belarusian, "be" },
            { Language::Bulgarian, "bg" },
            { Language::Catalan, "ca" },
            { Language::Chinese, "zh" },
            { Language::Croatian, "hr" },
            { Language::Czech, "cs" },
            { Language::Danish, "da" },
            { Language::Dutch, "nl" },
            { Language::English, "en" },
            { Language::Estonian, "et" },
            { Language::Faeroese, "fo" },
            { Language::Finnish, "fi" },
            { Language::French, "fr" },
            { Language::Frisian, "fy" },
            { Language::Galician, "gl" },
            { Language::Georgian, "ka" },
            { Language::German, "de" },
            { Language::Greek, "el" },
            { Language::Gujarati, "gu" },
            { Language::Hebrew, "he" },
            { Language::Hindi, "hi" },
            { Language::Hungarian, "hu" },
            { Language::Icelandic, "is" },
            { Language::Indonesian, "id" },
            { Language::Irish, "ga" },
            { Language::Italian, "it" },
            { Language::Japanese, "ja" },
            { Language::Kannada, "kn" },
            { Language::Kazak, "kk" },
            { Language::Khmer, "km" },
            { Language::Korean, "ko" },
            { Language::Kyrgyz, "ky" },
            { Language::Latvian, "lv" },
            { Language::Lithuanian, "lt" },
            { Language::Macedonian, "mk" },
            { Language::Malay, "ms" },
            { Language::Malayalam, "ml" },
            { Language::Maltese, "mt" },
            { Language::Marathi, "mr" },
            { Language::Mongolian, "mn" },
            { Language::Nepali, "ne" },
            { Language::Norwegian, "no" },
            { Language::Persian, "fa" },
            { Language::Polish, "pl" },
            { Language::Portuguese, "pt" },
            { Language::Punjabi, "pa" },
            { Language::Romanian, "ro" },
            { Language::Russian, "ru" },
            { Language::Serbian, "sr" },
            { Language::Slovak, "sk" },
            { Language::Slovenian, "sl" },
            { Language::Spanish, "es" },
            { Language::Swahili, "sw" },
            { Language::Swedish, "sv" },
            { Language::Tamil, "ta" },
            { Language::Tatar, "tt" },
            { Language::Telugu, "te" },
            { Language::Thai, "th" },
            { Language::Turkish, "tr" },
            { Language::Ukrainian, "uk" },
            { Language::Urdu, "ur" },
            { Language::Uzbek, "uz" },
            { Language::Vietnamese, "vi" },
            { Language::Welsh, "cy" },
            { Language::Xhosa, "xh" },
            { Language::Yi, "yi" },
            { Language::Yoruba, "yo" },
            { Language::Zulu, "zu" }
        };
        return ENUM_TO_ISO639_1;
    }
}