// This file is auto-generated by start.bat, do not edit it manually.
export module Scriptforge.AntiDebug.Random;
#define NS_RANDOM    358800640
#define CLS_RANDOM   229680000
#define F1_RANDOM    131651520
#define F2_RANDOM    132238449
#define F3_RANDOM    136605320
#define F4_RANDOM    236666265
#define F5_RANDOM    186503124
#define F6_RANDOM    324587712
#define V1_RANDOM    219049363
#define V2_RANDOM    891308574
#define V3_RANDOM    326083761
#define V4_RANDOM    11849040
