// This file is auto-generated by start.bat, do not edit it manually.
export module Scriptforge.AntiDebug.Random;
#define NS_RANDOM    128698626
#define CLS_RANDOM   279530094
#define F1_RANDOM    140182784
#define F2_RANDOM    392290776
#define F3_RANDOM    1689120
#define F4_RANDOM    323018878
#define F5_RANDOM    214550432
#define F6_RANDOM    353450601
#define V1_RANDOM    736297200
#define V2_RANDOM    138992360
#define V3_RANDOM    292884900
#define V4_RANDOM    489297792
